### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by dmittrey** [Vakzu/musical-wars-backend#29]
- 1 Блок (страница регистрации/входа)
**Front:**
- [ ] Изменить ui для страниц входа и регистрации, сохранив функциональные требования
- [ ] Сделать валидацию на второе поле и наложить ограничения на символы

- 2 Блок (Основная страница)
**Front:**
- [ ] Привести в порядок ui, сохранив функциональные требования
- [ ] Refactor js
- [ ] Добавить кнопку перейти в статистику
- [ ] Добавить кнопку выхода
**Back:**
- [x] Добавить ручку для перехода на статистику

- 3 Блок (Лобби)
**Front:**
- [ ] Привести в порядок ui, сохранив функциональные требования
- [ ] Реализовать выставление готовности
**Back:**
- [x] Протестировать логику выбора эффектов
- [x] Слить изменения в feature ветку(я хочу посмотреть)
- [x] Сделать выставление готовности
- [x] Хранение состояния каждого героя в лобби на back-end слое

- 4 Блок (Fight)
**Front:**
- [ ] Анимация атак
- [ ] Анимация персонажей
- [ ] Кнопка Leave
**Back:**
- [x] Написать логику самого сражения(late)

- 5 Блок(Статистика)
**Front:**
- [ ] ... 
- [x] Написать sql функции для метрик
**Back:**
- [x] Мы расписывали какие отправить метрики(сделать ручки для них)

Метрики:
- [x] Кол-во сыгранных игр
- [x] Кол-во побед
- [x] Среднее занимаемое место
- [x] Время последней игры
